import os

TWILIO_ACCOUNT_SID = os.environ['TWILIO_ACCOUNT_SID']
TWILIO_AUTH_TOKEN = os.environ['TWILIO_AUTH_TOKEN']

SENDER_PHONE_NUMBER = os.environ['SENDER_PHONE_NUMBER']
RECIPIENT_PHONE_NUMBER = os.environ['RECIPIENT_PHONE_NUMBER']

MESSAGE = os.environ['MESSAGE']
PERIOD_SECONDS = int(os.environ['PERIOD_SECONDS'])
